package Hibernate;
// Generated 27-ene-2016 23:03:44 by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private String cedula;
     private String telefono;
     private String foto;
     private String rango;
     private String clave;
     private String email;

    public Admin() {
    }

    public Admin(String nombre, String apellido, String cedula, String telefono, String foto, String rango, String clave, String email) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
       this.telefono = telefono;
       this.foto = foto;
       this.rango = rango;
       this.clave = clave;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getRango() {
        return this.rango;
    }
    
    public void setRango(String rango) {
        this.rango = rango;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


