package Hibernate;
// Generated 27-ene-2016 23:03:44 by Hibernate Tools 4.3.1



/**
 * Alquilado generated by hbm2java
 */
public class Alquilado  implements java.io.Serializable {


     private Integer id;
     private String nombreCliente;
     private String apellidoCliente;
     private String cedulaCliente;
     private String fotoCliente;
     private String marcaAuto;
     private String modeloAuto;
     private String codigoAuto;
     private String fotoAuto;
     private String rentadoDia;
     private String paraEntregar;
     private String regresadoDia;
     private String estado;

    public Alquilado() {
    }

	
    public Alquilado(String nombreCliente, String apellidoCliente, String cedulaCliente, String fotoCliente, String marcaAuto, String modeloAuto, String codigoAuto, String fotoAuto) {
        this.nombreCliente = nombreCliente;
        this.apellidoCliente = apellidoCliente;
        this.cedulaCliente = cedulaCliente;
        this.fotoCliente = fotoCliente;
        this.marcaAuto = marcaAuto;
        this.modeloAuto = modeloAuto;
        this.codigoAuto = codigoAuto;
        this.fotoAuto = fotoAuto;
    }
    public Alquilado(String nombreCliente, String apellidoCliente, String cedulaCliente, String fotoCliente, String marcaAuto, String modeloAuto, String codigoAuto, String fotoAuto, String rentadoDia, String paraEntregar, String regresadoDia, String estado) {
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.cedulaCliente = cedulaCliente;
       this.fotoCliente = fotoCliente;
       this.marcaAuto = marcaAuto;
       this.modeloAuto = modeloAuto;
       this.codigoAuto = codigoAuto;
       this.fotoAuto = fotoAuto;
       this.rentadoDia = rentadoDia;
       this.paraEntregar = paraEntregar;
       this.regresadoDia = regresadoDia;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getCedulaCliente() {
        return this.cedulaCliente;
    }
    
    public void setCedulaCliente(String cedulaCliente) {
        this.cedulaCliente = cedulaCliente;
    }
    public String getFotoCliente() {
        return this.fotoCliente;
    }
    
    public void setFotoCliente(String fotoCliente) {
        this.fotoCliente = fotoCliente;
    }
    public String getMarcaAuto() {
        return this.marcaAuto;
    }
    
    public void setMarcaAuto(String marcaAuto) {
        this.marcaAuto = marcaAuto;
    }
    public String getModeloAuto() {
        return this.modeloAuto;
    }
    
    public void setModeloAuto(String modeloAuto) {
        this.modeloAuto = modeloAuto;
    }
    public String getCodigoAuto() {
        return this.codigoAuto;
    }
    
    public void setCodigoAuto(String codigoAuto) {
        this.codigoAuto = codigoAuto;
    }
    public String getFotoAuto() {
        return this.fotoAuto;
    }
    
    public void setFotoAuto(String fotoAuto) {
        this.fotoAuto = fotoAuto;
    }
    public String getRentadoDia() {
        return this.rentadoDia;
    }
    
    public void setRentadoDia(String rentadoDia) {
        this.rentadoDia = rentadoDia;
    }
    public String getParaEntregar() {
        return this.paraEntregar;
    }
    
    public void setParaEntregar(String paraEntregar) {
        this.paraEntregar = paraEntregar;
    }
    public String getRegresadoDia() {
        return this.regresadoDia;
    }
    
    public void setRegresadoDia(String regresadoDia) {
        this.regresadoDia = regresadoDia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


