package Hibernate;
// Generated 27-ene-2016 23:03:44 by Hibernate Tools 4.3.1



/**
 * Autos generated by hbm2java
 */
public class Autos  implements java.io.Serializable {


     private Integer id;
     private String marca;
     private String modelo;
     private String ano;
     private String codigo;
     private String foto1;
     private String foto2;
     private String foto3;
     private String foto4;
     private String foto5;
     private String estado;
     private String color;
     private String taza;
     private String motivo;

    public Autos() {
    }

	
    public Autos(String marca, String modelo, String ano, String codigo, String foto1, String estado, String color, String taza) {
        this.marca = marca;
        this.modelo = modelo;
        this.ano = ano;
        this.codigo = codigo;
        this.foto1 = foto1;
        this.estado = estado;
        this.color = color;
        this.taza = taza;
    }
    public Autos(String marca, String modelo, String ano, String codigo, String foto1, String foto2, String foto3, String foto4, String foto5, String estado, String color, String taza, String motivo) {
       this.marca = marca;
       this.modelo = modelo;
       this.ano = ano;
       this.codigo = codigo;
       this.foto1 = foto1;
       this.foto2 = foto2;
       this.foto3 = foto3;
       this.foto4 = foto4;
       this.foto5 = foto5;
       this.estado = estado;
       this.color = color;
       this.taza = taza;
       this.motivo = motivo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getFoto1() {
        return this.foto1;
    }
    
    public void setFoto1(String foto1) {
        this.foto1 = foto1;
    }
    public String getFoto2() {
        return this.foto2;
    }
    
    public void setFoto2(String foto2) {
        this.foto2 = foto2;
    }
    public String getFoto3() {
        return this.foto3;
    }
    
    public void setFoto3(String foto3) {
        this.foto3 = foto3;
    }
    public String getFoto4() {
        return this.foto4;
    }
    
    public void setFoto4(String foto4) {
        this.foto4 = foto4;
    }
    public String getFoto5() {
        return this.foto5;
    }
    
    public void setFoto5(String foto5) {
        this.foto5 = foto5;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getTaza() {
        return this.taza;
    }
    
    public void setTaza(String taza) {
        this.taza = taza;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


